version: '3.7'
services:
  frontend:
    image: asv-frontend
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: asv-frontend
    tty: true
    ports:
      - 4200:4200
    networks:
      - asv-network
    privileged: true
    depends_on: 
      - backend
  backend:
    image: asv-backend
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: asv-backend
    tty: true
    expose:
      - 8080
    networks: 
      - asv-network
    depends_on: 
      - database
  database:
    image: asv-postgres
    build:
      context: .
      dockerfile: docker/Dockerfile.database
    container_name: asv-postgres
    tty: true
    expose:
      - 5432
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks: 
      - asv-network
networks:
  asv-network:
    driver: bridge