/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CompetitionDTO } from './competitionDTO';

export interface TeamDTO { 
    competitionsDTO?: Array<CompetitionDTO>;
    country?: string;
    id?: number;
    idHistoricalRivalTeam?: number;
    name?: string;
    nameHistRivalTeam?: string;
    numChampionsLeague?: number;
    shieldPhoto?: string;
}