/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserDTO { 
    birthDate?: Date;
    email?: string;
    id?: number;
    lastName?: string;
    name?: string;
    password?: string;
    phone?: string;
    roles?: Array<UserDTO.RolesEnum>;
    username?: string;
}
export namespace UserDTO {
    export type RolesEnum = 'ROLE_ADMIN' | 'ROLE_CLIENT';
    export const RolesEnum = {
        ADMIN: 'ROLE_ADMIN' as RolesEnum,
        CLIENT: 'ROLE_CLIENT' as RolesEnum
    };
}